apiVersion: apps/v1beta2 # error with v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: 056598417982.dkr.ecr.us-east-2.amazonaws.com/weatherapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
